config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  validates :name, :weight, :width, :height, :depth, :sku, presence: true
  validates :sku, length: {is: 20}
  validates :weight, :height, :width, :depth, numericality: {greater_than: 0}
  validates :sku, uniqueness: true
  belongs_to :supplier
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :registration_number, :brand_name, :full_address, :email, presence: true
  validates :registration_number, length: {is: 13}
  validates :registration_number, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :code, :area, :description, :address, :cep, :city, presence: true
  validates :code, uniqueness: true 
  validates :cep, format: {with:/\d{5}-\d{3}\Z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  
  def index
    @product_models = ProductModel.all
  end
  
  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    @suppliers = Supplier.all
    product_model_params = params.require(:product_model).permit(:name, :height, :width, 
                                                                :depth, :weight, :sku, :supplier_id)

    @product_model = ProductModel.new(product_model_params)
  if
    @product_model.save

    redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso.'
  else
    flash.now[:notice] = 'Não foi possível cadastrar o modelo do produto.'
    render 'new'
  end
  
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end
  def show
    @suppliers = Supplier.find(params[:id])
  end
  
  def new
    @suppliers = Supplier.new()
  end
  
  def edit
    @suppliers = Supplier.find(params[:id])
  end
  
  def update
    p = params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, 
      :full_address, :city, :state, :email)
      @suppliers = Supplier.find(params[:id])
      
      if @suppliers.update(p)
        redirect_to suppliers_path(@suppliers.id), notice: 'cadastro do fornecedor atualizado com sucesso'
      else
        flash[:notice] = 'Não foi possivel atualizar o cadastro do fornecedor'
        render 'edit'
      end
  end
    
    def create 
      p = params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, 
        :full_address, :city, :state, :email)
        @suppliers = Supplier.new(p)
        if @suppliers.save()
          flash[:notice] = "Fornecedor cadastrado com sucesso."
          redirect_to suppliers_path
        else
          flash.now[:notice] = 'Fornecedor não cadastrado'
          render 'new'
        end
    end
      private
      
      def set_supplier
        @supplier = Supplier.find(params[:id])
      end
      
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only:[:show, :edit, :update, :destroy]
  def show
  end
  
  def new
    @warehouse = Warehouse.new()
  end
  
  def destroy
    @warehouse.destroy
    redirect_to root_path, notice: 'Galpão removido com sucesso'
  end
  
  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save()
      flash[:notice] = "Galpão cadastrado com sucesso."
      redirect_to root_path
    else
      flash.now[:notice] = 'Galpão não cadastrado'
      render 'new'
    end
    
  end
  
  def edit
    
  end
  
  def update
    if @warehouse.update(warehouse_params)
      redirect_to warehouse_path(@warehouse.id), notice: 'Galpão atualizado com sucesso'
    else
      flash.now[:notice] = 'Não foi possivel atualizar o galpão'
      render 'edit'
    end
  end
  
  
  private
  
  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end
  
  def warehouse_params
    params.require(:warehouse).permit(:name, :code, :city, :area, 
      :cep, :description, :address )
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section id="warehouses">
<div>
  <%= link_to('Cadastrar Galpão', new_warehouse_path) %>
</div>
<% @warehouses.each do |w| %>
<div>
    <h3> <%= link_to(w.name, warehouse_path(w.id)) %> </h3>
    <dl>
      <dt>Código:</dt>
        <dd><%= w.code %> </dd>
      <dt>Cidade:</dt>
        <dd><%= w.city %></dd>
      <dt>Área:</dt>
        <dd><%= w.area %> m2</dd>
    </dl>
</div>
<% end %>

<% if @warehouses.empty? %>
  <p>Não existem galpões cadastrados</p>
<%end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <header>
    <h1>Galpões & Estoque</h1>
  </header>
  <main>
  <nav>
  <%= link_to 'Fornecedores', suppliers_path %>
  <%= link_to 'Modelos de Produto', product_models_path %>

  <% if user_signed_in? %>
  <%= current_user.email%>
  <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
  <%else%>
  <%= link_to 'Entrar', new_user_session_path %>
  <%end%>
  </nav>
  <%= flash[:notice] %>
    <%= yield %>
  </main>
  </body>
</html>

app/views/product_models/index.html.erb
<h1> Modelo de Produtos </h1>
<%= link_to 'Cadastrar Novo', new_product_model_path%>
<% if @product_models.any? %>


<% @product_models.each do |pm| %>
<div>
  <h2> <%= pm.name %> </h2>
  <dl>
    <dt>SKU</dt>
    <dd><%= pm.sku %> </dd>
    <dt> 
    <dd><%= pm.supplier.brand_name %> </dd>
  <dl>
</div>
<%end%>

<%else%>
 <p> Nenhum modelo de produto cadastro.</p>
<%end%>

app/views/product_models/new.html.erb
<h1>Cadastrar novo modelo de produto</h1>

<%= form_with(model: @product_model) do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :weight, 'Peso' %>
    <%= f.number_field :weight %>
  </div>
  <div>
    <%= f.label :height, 'Altura' %>
    <%= f.number_field :height %>
  </div>
  <div>
    <%= f.label :depth, 'Profundidade' %>
    <%= f.number_field :depth %>
  </div>
  <div>
    <%= f.label :width, 'Largura' %>
    <%= f.number_field :width %>
  </div>
  <div>
    <%= f.label :sku, 'SKU' %>
    <%= f.text_field :sku %>
  </div>

  <div>
    <%= f.label :supplier_id, 'Fornecedor' %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>

    <%= f.submit 'Enviar' %>
<%end%>

app/views/product_models/show.html.erb
<h1><%= @product_model.name %></h1>
<dl>
  <dt>Fornecedor:</dt>
  <dd><%= @product_model.supplier.brand_name %></dd>
  <dt>Dimensão:</dt>
  <dd><%= @product_model.height%>cm x <%=@product_model.width%>cm x <%=@product_model.depth%>cm</dd>
  <dt>Peso:</dt>
  <dd><%= @product_model.weight%>g</dd>
  <dt>SKU:</dt>
  <dd><%= @product_model.sku%>g</dd>
</dl>

app/views/suppliers/_form.html.erb
<%= form_with(model: @suppliers) do |f|%>
  <div>
  <%= f.label :corporate_name %>
  <%= f.text_field :corporate_name %>
  </div>

  <div>
  <%= f.label :brand_name %>
  <%= f.text_field :brand_name %>
  </div>

  <div>
  <%= f.label :registration_number %>
  <%= f.text_field :registration_number %>
  </div>

  <div>
  <%= f.label :full_address %>
  <%= f.text_area :full_address %>
  </div>

  <div>
  <%= f.label :city %>
  <%= f.text_field :city %>
  </div>

  <div>
  <%= f.label :state %>
  <%= f.text_field :state %>
  </div>

  <div>
  <%= f.label :email %>
  <%= f.text_field :email %>
  </div>

  <div>
  <%= f.submit 'Enviar' %>
  </div>

<%end%>

app/views/suppliers/edit.html.erb
<p>Editar fornecedor<p>
<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Lista de Fornecedores</h1>
<div>
<%= link_to 'Cadastrar fornecedor', new_supplier_path %>
</div>


<% if @suppliers.any?%>
<table>
  <thead>
    <tr>
      <th>Nome<th>
      <th>Localização<th>
    </tr>
      </thead>
      <tbody>
        <% @suppliers.each do |supplier| %>
        <tr>
        <td><%= link_to supplier.brand_name, supplier%>
        <td><%=supplier.city%> - <%= supplier.state%>
        </tr>
        <% end %>
      </tr>
      </tbody>
    </table>
<% else %>
  <p> Não existem fornecedores cadastrados </p>
<% end %>


app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>
<% if (@suppliers.errors.any?)%>
<p>Fornecedor não pode ser cadastro devido aos seguintes erros: </p>
<ul>
  <%@suppliers.errors.full_messages.each do |msg|%>
  <li>
  <%= msg %>
  </li>
  <%end%>
</ul>

<%end%>
<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1> Fornecedor: <%= @suppliers.brand_name %> </h1>
<div>
<strong> Nome: <%= @suppliers.corporate_name %> </strong>
<strong> CNPJ: <%= @suppliers.registration_number %> </strong>
<strong> Endereço: <%= @suppliers.full_address %> </strong>
<strong> Cidade: <%= @suppliers.city %> </strong>
<strong> Estado: <%= @suppliers.state %> </strong>
<strong> Email: <%= @suppliers.email %> </strong>
</div>

<div>
<%= link_to('Voltar', suppliers_path)%>
</div>

<div>
<%= link_to('Editar', edit_supplier_path(@suppliers.id))%>
</div>

app/views/warehouses/_form.html.erb
<%= form_with(model: @warehouse) do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :code %>
  <%= f.text_field :code %>
  </div>

  <div>
  <%= f.label :city %>
  <%= f.text_field :city %>
  </div>

  <div>
  <%= f.label :area %>
  <%= f.number_field :area %>
  </div>

  <div>
  <%= f.label :address %>
  <%= f.text_field :address %>
  </div>

  <div>
  <%= f.label :cep %>
  <%= f.text_field :cep %>
  </div>

  <div>
  <%= f.label :description %>
  <%= f.text_area :description %>
  </div>

  <div>
  <%= f.submit 'Enviar'%>
  </div>
<%end%>

app/views/warehouses/edit.html.erb
<p>Editar Galpão</p>

<%= render 'form' %>

app/views/warehouses/new.html.erb
<h1>Novo Galpão</h1>
<% if (@warehouse.errors.any?)%>
<p>Galpão não pode ser cadastro devido aos seguintes erros: </p>
<ul>
  <%@warehouse.errors.full_messages.each do |msg|%>
  <li>
  <%= msg %>
  </li>
  <%end%>
</ul>

<%end%>
 
<%= render 'form' %>

app/views/warehouses/show.html.erb
<h1>Galpão <%= @warehouse.code %></h1>
<h2><%= @warehouse.description %></h2>
<div>
  <strong>nome: <%=@warehouse.name %> </strong>
  <strong>Código: <%=@warehouse.code %> </strong>
  <strong>Cidade: <%=@warehouse.city %> </strong>
  <strong>Area: <%=@warehouse.area %> m2 </strong>
  <strong>Endereço: <%=@warehouse.address %> , cep: <%= @warehouse.cep %></strong>
</div>

<%= link_to('Editar', edit_warehouse_path(@warehouse.id))%>
<%= button_to('Remover', warehouse_path(@warehouse.id), method: :delete)%>


<div>
<%= link_to('voltar', root_path)%>
</div>